import "bootstrap/dist/css/bootstrap.min.css";
import './globals.css'

import { Inter } from 'next/font/google'
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SaferMKT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Menu />
        {children}
      </body>
      <Script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js'
        integrity='sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz'
        crossOrigin='anonymous' />

    </html>
  )
}


function Menu() {
  return (
    <nav className="navbar navbar-expand-lg" style={{backgroundColor:'white'}}>
      <div className="container">
        <a className="navbar-brand" href="#">
          <img src="./images/logo-safer.jpeg" alt="Logo" width="129" height="150" className="d-inline-block align-text-top" />          
        </a>
        <ul className="nav justify-content-center">
          <li className="nav-item">
            <a className="nav-link active colorLink" aria-current="page" href="#">O que SaferMkt faz </a>
          </li>
          <li className="nav-item">
            <a className="nav-link colorLink" href="#">Benefícios</a>
          </li>
          <li className="nav-item">
            <a className="nav-link colorLink" href="#">Nossos Clientes</a>
          </li>
          <li className="nav-item">
            <a className="nav-link colorLink">Perguntas Frequentes</a>
          </li>
        </ul>

      </div>
    </nav>
  );
}