import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";

import { Inter } from 'next/font/google'
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SaferMKT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className} style={{backgroundColor:'black'}}>
        <Menu />
        {children}
      </body>
      <Script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js'
        integrity='sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz'
        crossOrigin='anonymous' />

    </html>
  )
}


function Menu() {
  return (
    <nav className="navbar navbar-expand-lg" style={{backgroundColor:'black'}}>
      <div className="container">
        <a className="navbar-brand" href="#">
          <img src="https://assets.turbologo.com/blog/pt/2019/11/19133546/EA-logo.png" alt="Logo" width="50" height="24" className="d-inline-block align-text-top" />
          SaferMKT
        </a>
        <ul className="nav justify-content-center">
          <li className="nav-item">
            <a className="nav-link active" aria-current="page" href="#">O que SaferMkt faz </a>
          </li>
          <li className="nav-item">
            <a className="nav-link" href="#">Benefícios</a>
          </li>
          <li className="nav-item">
            <a className="nav-link" href="#">Nossos Clientes</a>
          </li>
          <li className="nav-item">
            <a className="nav-link disabled">Perguntas Frequentes</a>
          </li>
        </ul>

      </div>
    </nav>
  );
}